kind: pipeline
type: kubernetes
name: default
steps:
  - name: test
    image: gradle:jdk13
    environment:
      REPO_USER:
        from_secret: REPO_USER
      REPO_PASSWORD:
        from_secret: REPO_PASSWORD
    commands:
      - gradle assemble
      - gradle check
